form/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
  path('', views.index, name='index'),
]

regdesk/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
  path('', views.index, name = 'regdesk_dashboard'),
  path('login/', views.login_admin, name='regdesk_login'),
  path('logout/', views.logout_admin, name='regdesk_logout'),
#  path('empresario', views.Empresariosf, name = 'empresario'),
#  path('startup', views.Startup, name = 'startup'),
  path('contingent_details', views.contingent_details, name = 'contingent_details'),
  path('hall_allotment', views.hall_allotment, name = 'hall_allotment'),          # Contingent Checkin
  path('con-checkout/', views.con_checkout, name='con_checkout'),                 # Contingent Checkout
  path('individual_details', views.AllDetails, name = 'individual_details'),
  path('individual', views.IndividualCheckIn, name = 'individual'),
  path('empstartup', views.EmpStartupCheckIn, name='empstartup'),
  path('professional', views.ProfessionalCheckIn, name='professional'),
  path('checkout', views.CheckOut, name='checkout'),
  path('offlinepay/', views.OfflinePay, name='offlinepay'),
  path('hall-dash', views.hallDashBoard, name='hall-dash'),
  path('hall-get/', views.getHalls, name='get-halls'),
  path('hall-con-in', views.hall_con_checkin, name='hall-con-in'),
  path('hall-checkin', views.hallCheckin, name='hall-checkin'),
  path('full',views.allAllotted, name='full')
]

regportal/urls.py
from django.contrib import admin
from django.urls import path, include
from registration import views as signup
from login import views as post_reg

# register, login, post-reg-1,post-reg-2, payment, travel, create-contingent, join-contingent, faq, contact 
# Registration & Login to be handled by registration app
# Post reg process to be handled by login app

urlpatterns = [
    # Admin Panel
    path('admin/', admin.site.urls),
    path('admin-panel/', include('ges_admin.urls')),
#     path('regdesk/', include('regdesk.urls')),
  

    # Registration and related functionality
    path('register/', signup.registerUser, name='register'),                     # Return a reg form on a get request
    path('activate/<str:uid>/<str:token>/', signup.activate, name='activate'),   # Email Verification of new users
    path('register/new/college', signup.college, name='newCollege'),             # Register colleges not in our database

    # Login & Logout
    path('login/', signup.loginUser, name='login'),
    path('logout/', signup.logoutUser, name='logout'),

    # Static Pages
    path('contact/', post_reg.contact, name='contact'),
#     path('contact_us/', post_reg.contact_us, name='contact_us'),

    path('faq/', post_reg.faq, name='faq'),

    # Post Registration and related functionality
    path('', post_reg.home, name='home'),
    path('payment/', include('payment.urls')),
    path('dashboard/', post_reg.dashboard, name='dashboard'),
    path('join-contingent/', post_reg.join, name='join'),
    path('create-contingent/', post_reg.create, name='create'),
    path('view-contingent/', post_reg.view, name='view_contingent'),
    path('join-contingent/<str:contingent_id>/<str:contingent_captcha>', post_reg.join, name='join'),
    path('add-members/', post_reg.addMembers, name='add_members'),
  
    # URLS FOR PROCESSING AJAX REQUESTS (only via post requests)
    path('register/city', signup.getCity, name='getCity'),                       # Retrieve cities & return via AJAX
    path('register/college/<str:city>/', signup.getCollege, name='getCollege'),  # Retrieve colleges & return via AJAX
    path('register/validate', signup.validateUser, name='validate'),             # Validate & submit form data via AJAX
    path('validate/post-reg-startup', post_reg.validatestartup, name='validatestartup'),
    path('validate/post-reg-empresario', post_reg.validateempresario, name='validateempresario'),
    path('validate/post-reg-regular', post_reg.validateregular, name='validateregular'),
    path('validate/travel-details', post_reg.validatetravel, name='validatetravel'),
    path('create-contingent/validate', post_reg.validate_create_contingent, name='validate_create_contingent'),  
    path('add-members/validate', post_reg.validate_add_members, name='validate_add_members'),  
    
    path('regdesk/', include('regdesk.urls')),
]

regdesk/models.py
from django.db import models
from django.contrib.auth.models import User
from registration.models import Data
# Create your models here.

class MaleHall(models.Model):
  name = models.CharField(max_length=25)
  left = models.IntegerField(default=0)
  capacity = models.IntegerField(default=0)

  def __str__(self):
    return str(self.name)
  
  def inc(self, count = 1):
    self.left = self.left - count
    self.save()
    
  def dec(self, count = 1):
    self.left = self.left + count
    self.save()


class FemaleHall(models.Model):
  name = models.CharField(max_length=25)
  left = models.IntegerField(default=0)
  capacity = models.IntegerField(default=0)

  def __str__(self):
    return str(self.name)

  def inc(self, count = 1):
    self.left = self.left - count
    self.save()

  def dec(self, count = 1):
    self.left = self.left + count
    self.save()

  
class Allotment(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  userdata = models.ForeignKey(Data, on_delete=models.CASCADE)
  male_hall = models.ForeignKey(MaleHall, on_delete=models.CASCADE, null=True)
  female_hall = models.ForeignKey(FemaleHall, on_delete=models.CASCADE, null=True)
  hall_stat = models.CharField(max_length = 1, default = 0)

  def __str__(self):
    return str(self.user) + " " + str(self.male_hall) + " " + str(self.female_hall)

  def hall_checkin(self):
    self.hall_stat = 1
    self.save()

  def hall_checkout(self):
    self.hall_stat = 0
    self.save()
  
  def save(self, *args, **kwargs):
    self.userdata = Data.objects.get(user = self.user)
    super().save(*args, **kwargs)  # Call the "real" save() method.



class AltAllotment(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  userdata = models.ForeignKey(Data, on_delete=models.CASCADE)
  male_hall = models.ForeignKey(MaleHall, on_delete=models.CASCADE, null=True)
  male_num = models.IntegerField(null=True, default=0)
  female_hall = models.ForeignKey(FemaleHall, on_delete=models.CASCADE, null=True)
  female_num = models.IntegerField(null=True,default=0)
  category = models.CharField(max_length=20)
  hall_stat = models.CharField(max_length = 1, default = 0)
  def __str__(self):
    return str(self.user) + " " + str(self.category) + " " + str(self.male_hall) + " " +str(self.female_hall)
  
  def hall_checkin(self):
    self.hall_stat = 1
    self.save()

  def hall_checkout(self):
    self.hall_stat = 0
    self.save()
  
  
  def save(self, *args, **kwargs):
    self.userdata = Data.objects.get(user = self.user)
    super().save(*args, **kwargs)  # Call the "real" save() method.



class OfflinePayment(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  amount = models.CharField(max_length = 10, null = True)
  method = models.CharField(max_length=126, null = True)
  time = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    return 'GES ID ' +str(self.user.pk)+ ', INR ' +str(self.amount)

ges_admin/forms.py
from django import forms


class AdminLogin(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Admin Username', 'required': 'true', 'autofocus': 'true'}))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password here.', 'required':'true'}))
    city = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter city'}))

login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from registration.models import Data, Contingent, College
from .models import PostRegStartup, PostRegEmpresario, PostReg,Travel
from .forms import PostRegStartupForm, CoMeetForm, PExpoForm, SCampForm, EPitchForm, PostRegEmpresarioForm, PostRegForm, CreateContingentForm, JoinContingentForm, TravelForm

# Always pass user & userdata in context of every function which renders any template as base.html depends on it.
# Give login_required decorator at beginning of each function to ensure user does not see that page without logging in.
# Contingent option is enabled if and only if the participant is on stage 1.
# TODO: create & join contingent only accessible on stage 1 else redirect

@login_required(login_url='/login/')
def create(request):
    try:
        user = User.objects.get(username=request.session['email'])
        userdata = Data.objects.get(user=user)
        if userdata.contingent:
          return redirect('home')
        form = CreateContingentForm(initial={'gesid1': user.id})

        context = {
            'user': user,
            'userdata': userdata,
            'form': form
        }
        return render(request, 'login/create.html', context)
    except KeyError:
        raise KeyError

        
@login_required(login_url='/login/')
def view(request):
    try:              # Minimum contingent size should be 5 and can only join/create a contingent if they are on stage 1
        user = User.objects.get(username=request.session['email'])
        userdata = Data.objects.get(user=user)
        if not userdata.admin:
          redirect('home')

        contingent_id = userdata.admin
        qs = Data.objects.filter(contingent=contingent_id)
        members = []
        for data in qs:
          user_info = []
          user_info.append(data.user)
          user_info.append(data)
          members.append(user_info)
        size = qs.count()
        contingent = Contingent.objects.get(id=contingent_id)
        context = {
            'members': members,
            'contingent': contingent,
            'size': size,
            'user': user,
            'userdata': userdata,
        }
        return render(request, 'login/contingent.html', context)
    except KeyError:
        raise KeyError

        
def join(request, contingent_id='', contingent_captcha=''):
  if request.method == 'POST':
    contingent_id = request.POST['uid']
    contingent_captcha = request.POST['captcha']
    post = True
    contForm = JoinContingentForm(request.POST)
  
  else:
    post = False
  
  try:
    user = User.objects.get(username=request.session['email'])
    userLoggedIn = True
    userdata = Data.objects.get(user=user)
  except KeyError:
    userLoggedIn = False   
    
  if userLoggedIn and userdata.session_type:
    return redirect('home')
  
  if userLoggedIn and userdata.contingent:
    context = {
      'success': 'Already added to a contingent',
      'successMessage': 'You are already a part of the contingent.'
      }
    return render(request, 'login/join.html', context)

  if contingent_id and contingent_captcha:
    inviteLink = 'http://reg-ges.ecell-iitkgp.org/join-contingent/'+str(contingent_id)+'/'+str(contingent_captcha)
   
    try:
      contingent = Contingent.objects.get(link=inviteLink)
      contingentExists = True
    except Contingent.DoesNotExist:
      contingentExists = False
  
    if contingentExists:
      if contingent.stage > 1:
        context = {
          'error': 'Unable to join',
          'errorMessage': 'This contingent cannot accept any more members.'
          }
        return render(request, 'login/join.html', context)
  
    if userLoggedIn and contingentExists:
      if userdata.college == contingent.college.college:
        userdata.contingent = contingent.id
        userdata.save()
        contingent.size = contingent.size + 1
        contingent.save()
        context = {
          'success': 'Added to the Contingent',
          'successMessage': 'You have been successfully added to the contingent.'
          }
        return render(request, 'login/join.html', context)
      
      else:
        context = {
          'error': 'Unable to join',
          'errorMessage': 'You and this contingent are registered on a different college. Thus, you cannot join this contingent.'
          }
        return render(request, 'login/join.html', context)
        
    
    elif userLoggedIn and not contingentExists:
      if post:
        context = {
          'error': 'Invalid Credentials',
          'errorMessage': 'You have entered invalid ID & Password.',
          'form': contForm
        }
      else:
        context = {
          'error': 'Broken Invite Link',
          'errorMessage': 'This invitation link is broken. Please check the link.'
          }
      return render(request, 'login/join.html', context)
    
    elif contingentExists and not userLoggedIn:
      return HttpResponseRedirect('/login/?next=/join-contingent/'+str(contingent_id)+'/'+str(contingent_captcha))
    
    else:
      redirect('home')
    
  else:
    if userLoggedIn:
      contForm = JoinContingentForm()
      context = {
        'form': contForm,
        'user': user,
        'data': userdata
      }
      return render(request, 'login/join.html', context)
    else:
      return redirect('home')


@login_required(login_url='/login/')
@require_GET
def addMembers(request):
    try:
        user = User.objects.get(username=request.session['email'])
        userdata = Data.objects.get(user=user)
        if not userdata.admin:
          redirect('home')
        context = {}
        return render(request, 'login/add.html', context)
    except KeyError:
        raise KeyError


# Home view will be redirect to corresponding view depending on stage, as we dont want url to change
@login_required(login_url='/login/')
def home(request):
    user = User.objects.get(username=request.session['email'])
    userdata = Data.objects.get(user=user)

    if userdata.stage == 0:
        return post_reg(request, user, userdata)

    elif userdata.stage == 1:
        return redirect('payment_checkout')

    elif userdata.stage == 2:
        return travel(request, user, userdata)

    else:
        return redirect('dashboard')


@login_required(login_url='/login/')
def dashboard(request):
    user = User.objects.get(username=request.session['email'])
    userdata = Data.objects.get(user=user)
    context = {
        'user': user,
        'userdata': userdata
    }

    if userdata.contingent != 0:
        size = Data.objects.filter(contingent=userdata.contingent).count()
        context['teamsize'] = size
        return render(request, 'login/dashboard.html', context)

    elif userdata.category == 'Startup':
        size = PostRegStartup.objects.get(user=user).size
        context['teamsize'] = size
        return render(request, 'login/dashboard.html', context)

    elif userdata.category == 'Empresario Semi-Finalists':
        size = PostRegEmpresario.objects.get(user=user).size
        context['teamsize'] = size
        return render(request, 'login/dashboard.html', context)

    context = {
        'user': user,
        'userdata': userdata
    }
    return render(request, 'login/dashboard.html', context)


@login_required(login_url='/login/')
def post_reg(request, user, userdata):
    context = {
        'user': user,
        'userdata': userdata,
    }

    if userdata.category == 'Startup':
        form = PostRegStartupForm()
        context['form'] = form

        PostRegData = PostRegStartup.objects.get(user=user)
        eventType = PostRegData.events.split('-')
        for event in eventType:
            if event == 'pexpo':
                pexpo = PExpoForm()
                context['pexpo'] = pexpo
            elif event == 'comeet':
                comeet = CoMeetForm()
                context['comeet'] = comeet
            elif event == 'epitch':
                epitch = EPitchForm()
                context['epitch'] = epitch
            else:
                scamp = SCampForm()
                context['scamp'] = scamp

        return render(request, 'login/post_reg_startup.html', context)

    elif userdata.category == 'Empresario Semi-Finalists':
        form = PostRegEmpresarioForm()
        context['form'] = form

        return render(request, 'login/post_reg_empresario.html', context)

    form = PostRegForm()
    context['form'] = form
    return render(request, 'login/post_reg.html', context)


def payment(request, user, userdata):
    context = {
        'user': user,
        'userdata': userdata
    }
    return render(request, 'login/payment.html', context)


def travel(request, user, userdata):
    form = TravelForm()
    context = {
        'user': user,
        'userdata': userdata,
        'form': form 
      }
    return render(request, 'login/travel.html', context)
  
  
def faq(request):
    try:
      email = request.session.get('email')
      user = User.objects.get(username=request.session['email'])
      userdata = Data.objects.get(user=user)
      context = {
          'base_path': 'login/base.html',
          'user': user,
          'userdata': userdata
      }
      return render(request, 'login/faq.html', context)
    except KeyError:
      return render(request, 'login/faq.html', {'base_path': 'registration/base.html'})
    
def contact(request):
    try:
      email = request.session.get('email')
      user = User.objects.get(username=request.session['email'])
      userdata = Data.objects.get(user=user)
      context = {
          'base_path': 'login/base.html',
          'user': user,
          'userdata': userdata
      }

templates/regdesk/details.html
<!DOCTYPE html>

<html lang="en-us">
<head>
    <title>GES | Administration</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/admin/css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/admin/css/login.css' %}"/>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static '/admin/css/responsive.css' %}"/>
    <script type="text/javascript" src="{% static '/assets/js-core/jquery-core.js' %}"></script>
    <meta name="robots" content="NONE,NOARCHIVE"/>

    <style>
        #container{
            width:80% !important;
        }
        #id_city{
            clear: both;
            padding: 8px;
            width: 100%;
            box-sizing: border-box;
        }

        .hidden{
            display: none;
            visibility: hidden;
        }
    </style>
</head>


<body class=" login" data-admin-utc-offset="0">
    <div id="container">
        <div id="header">
            <div id="branding">
                <h1 id="site-name"><a href="{% url 'regdesk_dashboard' %}">Forms</a><span style="right: 6px;position: absolute;"><a href='{% url "regdesk_logout" %}'>Logout </a></span></h1>
            </div>
            <div >
                    {% if request.session.hall %}
                    <span id="site-name"><a href='{% url "hall-dash" %}'> Dashboard</a></span>
                    {% endif %}
            </div>
        </div>
        <div id="content" class="colM">
            {% if not request.session.hall %}
            <form action='{% url  "hall_allotment" %}' method='GET'>
                                <input type='hidden' name='redirect' value='{{ request.build_absolute_uri }}'>
                
                <div class='form-row'>
                        <p><input type="checkbox" id="checkinAll" >Select All</p>

                    <p>
                    Male students : {{male_num}}  
                    </p>
                
                    {% for student in students_male %}
                    <p>
                    <input class='checkinbox' type='checkbox' name='{{student.pk}}' value = '1'>{{student.name}}:  {{student.category}}
                    </p>
                    {% endfor %}
            
                    <p>
                    Female students : {{female_num}}  
                    </p> 
                    
                    {% for student in students_female %}
                    <p>
                    <input class='checkinbox' type='checkbox' name='{{student.pk}}' value = '1'>{{student.name}}:  {{student.category}}
                    </p>

                    {% endfor %}
                    <p>Male Hall</p>
                    <select name="m_hall">
                        {% for hall in male_halls %}
                            <option value='{{hall.name}}'>{{hall.name}}: {{hall.left}} Left</option>
                        {% endfor %}
                    </select>

                    <p>Female Hall</p>
                    <select name="f_hall">
                        {% for hall in female_halls %}
                            <option value='{{hall.name}}'>{{hall.name}}: {{hall.left}} Left</option>
                        {% endfor %}
                    </select> 
                </div>
                <input type='hidden' name='c_id' value='{{captcha}}'>
                <div class='submit-row'><input type='submit' value="Allot"></div>
        
            </form>

            {% endif %}
<br><hr><br>
        <p>Checked in: Info</p>
            {% if request.session.hall %}
                <form method='GET' action = '{% url "con_checkout" %}'>
                        <input type='hidden' name='redirect' value='{{ request.build_absolute_uri }}'>

                    
                <input type='hidden' name='c_id' value='{{captcha}}'>
                <div class="form-row">
                        <p><input type="checkbox" id="checkoutAll" >Select All</p>

                {% for stu in allotted %}
                {% if stu.male_hall.name == request.session.hall or stu.female_hall.name == request.session.hall %}

                {% if stu.hall_stat == '1' %}
                <p><input class="checkoutbox" type='checkbox' name='{{stu.user.pk}}' value = 'out'>{{stu.userdata.name}}: {{stu.userdata.category}}</p>
                {% endif %}
                {% endif %}
                {% endfor %}
                </div>
                <div class='submit-row'><input type='submit' value="Checkout Selected"></div>
                
                </form><br><br>
                
                <form method='GET' action = '{% url "hall-con-in" %}'>
                    <input type='hidden' name='redirect' value='{{ request.build_absolute_uri }}'>

                
            <input type='hidden' name='c_id' value='{{captcha}}'>
            <div class="form-row">
                    <p><input type="checkbox" id="checkinAll" >Select All</p>

            {% for stu in allotted %}
            {% if stu.male_hall.name == request.session.hall or stu.female_hall.name == request.session.hall %}

            {% if stu.hall_stat == '0' %}
            <p><input class="checkinbox" type='checkbox' name='{{stu.user.pk}}' value = '1'>{{stu.userdata.name}}: {{stu.userdata.category}}</p>
            {% endif %}
            {% endif %}
            {% endfor %}
            </div>
            <div class='submit-row'><input type='submit' value="CheckIn Selected"></div>
            
        </form>
    {% else %}

    {% for stu in checkedIn %}
    <p>{{stu.name}}: {{stu.category}}</p>
    {% endfor %}

    {% endif %}
    </div>
        <div id="footer"></div>
    </div>
<script>
$(document).ready(()=>{
   /* $('#checkinAll').click(()=>{
        console.log("just for check")
        if(this.checked){
            $('.checkinbox').each(function(){
                this.checked = true;
            })
        }
        else{
            $('.checkinbox').each(function(){
                this.checked = false;
            })
        }
    })

    $('#checkoutAll').click(()=>{
        if(this.checked){
            $('.checkoutbox').each(function(){
                this.checked = true;
            })
        }
        else{
            $('.checkoutbox').each(function(){
                this.checked = false;
            })
        }
    })*/


        $('#checkinAll').click(function(){
            if($(this).prop("checked")) {
                $(".checkinbox").prop("checked", true);
            } else {
                $(".checkinbox").prop("checked", false);
            }                
        });


        $('.checkinbox').click(function(){
            if($(".checkinbox").length == $(".checkinbox:checked").length) {
                $("#checkinAll").prop("checked", true);
            }else {
                $("#checkinAll").prop("checked", false);            
            }
        });

        $('#checkoutAll').click(function(){
            if($(this).prop("checked")) {
                $(".checkoutbox").prop("checked", true);
            } else {
                $(".checkoutbox").prop("checked", false);
            }                
        });


        $('.checkoutbox').click(function(){
            if($(".checkoutbox").length == $(".checkoutbox:checked").length) {
                $("#checkoutAll").prop("checked", true);
            }else {
                $("#checkoutAll").prop("checked", false);            
            }
        });


})
</script>

</body>
</html>

templates/regdesk/full.html
<!DOCTYPE html>

<html lang="en-us">
<head>
    <title>GES | Administration</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/admin/css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/admin/css/login.css' %}"/>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static '/admin/css/responsive.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/assets/widgets/datatable/datatable.css' %}">
    <script type="text/javascript" src="{% static '/assets/js-core/jquery-core.js' %}"></script>
    <meta name="robots" content="NONE,NOARCHIVE"/>

    <style>
        #container{
            width:80% !important;
        }
        #id_city{
            clear: both;
            padding: 8px;
            width: 100%;
            box-sizing: border-box;
        }

        .hidden{
            display: none;
            visibility: hidden;
        }
    </style>
</head>


<body class=" login" data-admin-utc-offset="0">
    <div id="container">
        <div id="header">
                <div id="branding">
                        <h1 id="site-name"><a href="{% url 'regdesk_dashboard' %}">Forms</a><span style="right: 6px;position: absolute;"><a href='{% url "regdesk_logout" %}'>Logout </a></span></h1>
                    </div>
                <div >
                        {% if request.session.hall %}
                        <span id="site-name"><a href='{% url "hall-dash" %}'> Dashboard</a></span>
                        {% endif %}
                </div>
        </div>
        <br><br>
        <div class='content'>
           <table id="datatable-responsive" class="table table-striped table-bordered responsive no-wrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Contingent Id</th>
                    <th>Hall</th>
                    <th>Status</th>
                    <th>Details</th>
                </tr>
            </thead>
            <tbody>
                {% for ind in allotAll %}
                <tr>
                    <th>{{ind.user}}</th>
                    <th>{{ind.userdata.name}}</th>
                    <th>{{ind.userdata.category}}</th>
                    <th>{{ind.userdata.contingent}}</th>
                    <th>{{ind.male_hall}} / {{ind.female_hall}}</th>
                    <th>{% if ind.hall_stat == '0' %} Not Checked In {% else %} CheckedIn {% endif %}</th>
                    <th><a href='/regdesk/individual_details?i_id={{ind.user.pk}}'><button>Details</button></a></th>
                </tr>
                {% endfor %}

                {% for ind in allotAlt %}
                <tr>
                    <th>{{ind.user}}</th>
                    <th>{{ind.userdata.name}}</th>
                    <th>{{ind.userdata.category}}</th>
                    <th>{{ind.userdata.contingent}}</th>
                    <th>{{ind.male_hall}} / {{ind.female_hall}}</th>
                    <th>{% if ind.hall_stat == '0' %} Not Checked In {% else %} CheckedIn {% endif %}</th>
                    <th><a href='/regdesk/individual_details?i_id={{ind.user.pk}}'><button>Details</button></a></th>
                </tr>
                {% endfor %}

            </tbody>

           </table>
            <br class="clear"/>
        </div>
        <div id="footer"></div>
    </div><script>
    $(document).ready(function () {
        $('#datatable-responsive').DataTable({
            responsive: true
        });
        $(document).ready(function () {
                    $('.dataTables_filter input').attr("placeholder", "Search...");
                });
    });</script>
    <script type="text/javascript" src="{% static '/assets/widgets/datatable/datatable.js' %}"></script>
    <script type="text/javascript" src="{% static '/assets/widgets/datatable/datatable-bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static '/assets/widgets/datatable/datatable-responsive.js' %}"></script>
    <script type="text/javascript" src="{% static '/assets/js-core/jquery-ui-widget.js' %}"></script>

</body>
</html>