form/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
  path('', views.index, name='index'),
]

payment/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
  path('', views.paymentCheckout, name='payment_checkout'),
]

regportal/urls.py
from django.contrib import admin
from django.urls import path, include
from registration import views as signup
from login import views as post_reg

# register, login, post-reg-1,post-reg-2, payment, travel, create-contingent, join-contingent, faq, contact 
# Registration & Login to be handled by registration app
# Post reg process to be handled by login app

urlpatterns = [
    # Admin Panel
    path('admin/', admin.site.urls),
    path('admin-panel/', include('ges_admin.urls')),
#     path('regdesk/', include('regdesk.urls')),
  

    # Registration and related functionality
    path('register/', signup.registerUser, name='register'),                     # Return a reg form on a get request
    path('activate/<str:uid>/<str:token>/', signup.activate, name='activate'),   # Email Verification of new users
    path('register/new/college', signup.college, name='newCollege'),             # Register colleges not in our database

    # Login & Logout
    path('login/', signup.loginUser, name='login'),
    path('logout/', signup.logoutUser, name='logout'),

    # Static Pages
    path('contact/', post_reg.contact, name='contact'),
#     path('contact_us/', post_reg.contact_us, name='contact_us'),

    path('faq/', post_reg.faq, name='faq'),

    # Post Registration and related functionality
    path('', post_reg.home, name='home'),
    path('payment/', include('payment.urls')),
    path('dashboard/', post_reg.dashboard, name='dashboard'),
    path('join-contingent/', post_reg.join, name='join'),
    path('create-contingent/', post_reg.create, name='create'),
    path('view-contingent/', post_reg.view, name='view_contingent'),
    path('join-contingent/<str:contingent_id>/<str:contingent_captcha>', post_reg.join, name='join'),
    path('add-members/', post_reg.addMembers, name='add_members'),
  
    # URLS FOR PROCESSING AJAX REQUESTS (only via post requests)
    path('register/city', signup.getCity, name='getCity'),                       # Retrieve cities & return via AJAX
    path('register/college/<str:city>/', signup.getCollege, name='getCollege'),  # Retrieve colleges & return via AJAX
    path('register/validate', signup.validateUser, name='validate'),             # Validate & submit form data via AJAX
    path('validate/post-reg-startup', post_reg.validatestartup, name='validatestartup'),
    path('validate/post-reg-empresario', post_reg.validateempresario, name='validateempresario'),
    path('validate/post-reg-regular', post_reg.validateregular, name='validateregular'),
    path('validate/travel-details', post_reg.validatetravel, name='validatetravel'),
    path('create-contingent/validate', post_reg.validate_create_contingent, name='validate_create_contingent'),  
    path('add-members/validate', post_reg.validate_add_members, name='validate_add_members'),  
    
    path('regdesk/', include('regdesk.urls')),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class PostRegStartup(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    details = models.TextField(max_length=600, null=True)
    website = models.URLField(max_length=100, null=True)
    size = models.IntegerField(null=True)
    events = models.CharField(max_length=100)
    startup_seedfund = models.BooleanField(default=False)
    startup_stage = models.CharField(max_length=100, null=True)
    intern_number = models.IntegerField(default=0)
    intern_stipend = models.CharField(max_length=100, null=True)
    intern_location = models.CharField(max_length=100, null=True)
    intern_profile = models.CharField(max_length=200, null=True)
    intern_duration = models.CharField(max_length=100, null=True)
    intern_description = models.CharField(max_length=100, null=True)
    epitch_sector = models.CharField(max_length=255, null=True)
    epitch_problem = models.TextField(max_length=600, null=True)
    epitch_market = models.TextField(max_length=600, null=True)
    epitch_revenue = models.TextField(max_length=600, null=True)
    epitch_compete = models.TextField(max_length=600, null=True)
    epitch_funds = models.TextField(max_length=600, null=True)
    epitch_deck = models.URLField(max_length=200, null=True)
    pexpo_type = models.CharField(max_length=20,null=True)
    pexpo_details = models.TextField(max_length=600,null=True)
    pexpo_demo = models.URLField(max_length=200,null=True)
    comeet_idea = models.BooleanField(default=False)
    comeet_skill_set = models.TextField(max_length=600, null=True)

    def __str__(self):
        return self.name


class PostRegEmpresario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    acco = models.BooleanField(default=True)
    size = models.IntegerField(default=1)

    def __str__(self):
        return self.user.username


class PostReg(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    startup = models.BooleanField(default=False)
    stage = models.CharField(max_length=100, null=True)
    profile = models.CharField(max_length=100, null=True)
    fav_startup = models.TextField(null=True)
    inspiration = models.TextField(null=True)

    def __str__(self):
        return self.user.username


class PaymentInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    amount = models.IntegerField()
#     size = models.IntegerField(default=1)
    txn_id = models.CharField(max_length=100)
    timestamp = models.DateTimeField()

    def __str__(self):
        return self.user.username+' - '+self.txn_id


class Travel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE )
    arrival = models.CharField(null=False, max_length= 50, default=0)
    departure = models.CharField(null=False, max_length= 50, default=0) 
    pnr = models.CharField(max_length=100, null=False, default=0)

    def __str__(self):
        return self.user.username


class Feedback(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    comments = models.TextField(max_length=300, null=True)
    download = models.BooleanField(default=False)

    def __str__(self):
        return self.user


class Halls(models.Model):
    name = models.CharField(max_length=100)
    location = models.TextField(max_length=150)
    capacity = models.IntegerField()

    def __str__(self):
        return self.name


# TODO: Separate model to store payment info associated with users by foreign key
# TODO: Model to store travel info and accommodation details of users.

payment/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import PostRegStartup, PostRegEmpresario, PostReg, Travel


EVENTS_CHOICES = (
    ('epitch', 'Elevator\'s Pitch'),
    ('pexpo', 'Product Expo'),
    ('comeet', 'Co-Founder\'s Meet'),
    ('startup', 'Startup Camp')
)

BOOL_CHOICES = (
    (True, 'Yes'),
    (False, 'No')
)

STARTUP_STAGE = (
    ('Idea', 'Ideation Phase'),
    ('proof', 'Proof of Concept'),
    ('op < 1', 'Operational (Less than 1 year)'),
    ('op > 1', 'Operational (More than 1 year)')
)

SKILL_SET = (
    ('web-d', 'Web Development'),
    ('app-d', 'Android/iOS Development'),
    ('iot', 'IOT'),
    ('marketing', 'Marketing'),
    ('operations', 'Operations'),
    ('sales', 'Sales'),
)

INTERN_CHOICE = (
    ('web-d', 'Web Development'),
    ('app-d', 'Android/iOS Development'),
    ('iot', 'IOT'),
    ('marketing', 'Marketing'),
    ('operations', 'Operations'),
    ('sales', 'Sales'),
)

PRODUCT_TYPE = (
    ('Hardware', 'Hardware'),
    ('Software', 'Software'),
)


class CreateContingentForm(forms.Form):
    gesid1 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the ges id of first member.', 'required':'true', 'disabled': 'disabled'}))
    gesid2 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the ges id of second member.', 'required':'true'}))
    gesid3 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the ges id of third member.', 'required':'true'}))
    gesid4 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the ges id of fourth member.', 'required':'true'}))
    gesid5 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the ges id of fifth member.', 'required':'true'}))
    
    class Meta:
        model = User
        labels = ['gesid1' ,'gesid2' ,'gesid3' ,'gesid4']
        
        
class JoinContingentForm(forms.Form):
  uid = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the contingent id.', 'required':'false'}))
  captcha = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter the contingent password', 'required':'true'}))
  
#   class Meta:
#     model = User
#     fields = ['ges_id1' , 'ges_pass1']
    

class PostRegStartupForm(forms.ModelForm):
    details = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Details about your company/startup here.'}))
    website = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'http://www.domain.com'}))
    size = forms.CharField(widget=forms.NumberInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Total number of people coming to attend GES.'}))

    class Meta:
        model = PostRegStartup
        fields = ['details', 'website', 'size']


class CoMeetForm(forms.ModelForm):
    comeet_idea = forms.ChoiceField(choices=BOOL_CHOICES, widget=forms.RadioSelect(attrs={'required': 'true', 'class': 'custom-radio', 'id': 'inlineRadio114'}))
    comeet_skill_set = forms.MultipleChoiceField(choices=SKILL_SET, widget=forms.CheckboxSelectMultiple(attrs={'class': 'custom-select', 'id': 'inlineCheckbox114'}))

    class Meta:
        model = PostRegStartup
        fields = ['comeet_idea', 'comeet_skill_set']


class PExpoForm(forms.ModelForm):
    pexpo_type = forms.ChoiceField(choices=PRODUCT_TYPE, widget=forms.RadioSelect(attrs={'required': 'true', 'class': 'custom-radio', 'id': 'inlineRadio114'}))
    pexpo_details = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Product Specific Details'}))
    pexpo_demo = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'A link to your product demo.'}))

    class Meta:
        model = PostRegStartup
        fields = ['pexpo_type', 'pexpo_details', 'pexpo_demo']


class EPitchForm(forms.ModelForm):
    epitch_sector = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'IOT, E-Commerce, etc.'}))
    epitch_problem = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control'}))
    epitch_market = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control'}))
    epitch_revenue = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control'}))
    epitch_compete = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control'}))
    epitch_funds = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control'}))
    epitch_deck = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Links can be Google drive, Youtube etc.,'}))

    class Meta:
        model = PostRegStartup
        fields = ['epitch_sector', 'epitch_problem', 'epitch_market', 'epitch_revenue', 'epitch_compete',
                  'epitch_funds', 'epitch_deck'
                 ]


class SCampForm(forms.ModelForm):
    intern_number = forms.CharField(widget=forms.NumberInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Number of interns required.'}))
    intern_stipend = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Min. Stipend(INR) - Max. Stipend(INR)'}))
    intern_location = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'City'}))
    intern_duration = forms.CharField(widget=forms.NumberInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Internship Duration (in weeks)'}))
    intern_description = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Details about your company/startup here.'}))
    intern_profile = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Web/app Development, marketing,etc.'}))
    startup_seedfund = forms.ChoiceField(choices=BOOL_CHOICES, widget=forms.RadioSelect(attrs={'required': 'true', 'class': 'custom-radio', 'id': 'inlineRadio114'}))
    startup_stage = forms.ChoiceField(choices=STARTUP_STAGE, widget=forms.Select(attrs={'required': 'true', 'class': 'custom-select', 'id': ''}))

    class Meta:
        model = PostRegStartup
        fields = ['startup_seedfund', 'startup_stage', 'intern_number', 'intern_stipend', 'intern_location',
                  'intern_duration', 'intern_description', 'intern_profile']


class PostRegEmpresarioForm(forms.ModelForm):
    acco = forms.ChoiceField(choices=BOOL_CHOICES, widget=forms.RadioSelect(attrs={'required': 'true', 'class': 'custom-radio', 'id': 'inlineRadio114'}))
    size = forms.CharField(widget=forms.NumberInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Number of people coming to attend GES.', 'min': 1}))

    class Meta:
        model = PostRegEmpresario
        fields = ['acco', 'size']


class PostRegForm(forms.ModelForm):
    startup = forms.ChoiceField(choices=BOOL_CHOICES, widget=forms.RadioSelect(attrs={'required': 'true', 'class': 'custom-radio', 'id': 'inlineRadio114'}))
    fav_startup = forms.CharField(widget=forms.Textarea(attrs={'required': 'true', 'class': 'form-control textarea-md'}))
    inspiration = forms.CharField(widget=forms.Textarea(attrs={'required': 'true', 'class': 'form-control textarea-md'}))
    stage = forms.ChoiceField(choices=STARTUP_STAGE, widget=forms.RadioSelect(attrs={'class': 'custom-radio', 'id': 'inlineRadio114'}))
    profile = forms.MultipleChoiceField(choices=INTERN_CHOICE, widget=forms.CheckboxSelectMultiple(attrs={'class': 'custom-select', 'id': 'inlineCheckbox114'}))

    class Meta:
        model = PostReg
        fields = ['startup', 'fav_startup', 'inspiration', 'stage', 'profile']
        
class TravelForm(forms.Form):
  arrival = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'dd/mm/yyyy HH:MM'}))
  departure = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'dd/mm/yyyy HH:MM'}))
#   arrival = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Enter your arrival date'}))
#   departure = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Enter your departure date'}))
  pnr = forms.CharField(widget=forms.TextInput(attrs={'required': 'true', 'class': 'form-control', 'placeholder': 'Enter your PNR number or Booking ID'}))
  

payment/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from registration.models import Data, Contingent
# Create your views here.


@login_required(login_url='/login/')
def paymentCheckout(request):
  try:
    user = User.objects.get(username=request.session['email'])
    userdata = Data.objects.get(user=user)
    response = eligible_to_pay(user)
    return HttpResponse(response)
  except KeyError:
    return redirect('login')

  
def eligible_to_pay(user):
  response = {}
  data = Data.objects.get(user=user)
  if data.stage == 1:
    if data.contingent and not data.admin:
      response['status'] = False
      response['message'] = 'Your Payment will be done by your contingent admin.'
    else:
      response['status'] = True
      response['message'] = 'Eligible to pay.'

  elif data.stage == 0:
    response['status'] = False
    response['message'] = 'Complete Post Registration Process to proceed for payment.'
  
  else:
    response['status'] = False
    response['message'] = 'Already Paid'
  return JsonResponse(response, safe=False)

templates/login/create.html
{% extends 'login/base.html' %}

{% block content %}
    <div class="panel" id="errorMessage" style="display:none;">
      <div class="panel-body">
          <h3 class="title-hero">Resolve the following errors.</h3>
          <div class="example-box-wrapper" id='errors'>
          </div>
      </div>
  </div>

<div class="panel" id="regForm">
    <div class="panel-body"> 
        <div class="alert alert-info">
            <div class="bg-blue alert-icon"><i class="glyph-icon icon-info"></i></div>
            <div class="alert-content">
                <h4 class="alert-title">Important Notice.</h4>
                <p>Add rest of the members to the contingent by asking them to fill join contingent form with the credentials provided upon successful creation.</p>
            </div>
        </div>
        <br>
        <h3 class="title-hero">Create a Contingent: GES 2019</h3>
        <marquee style="margin:30px; color: red; font-size:16px">**All members must belong to same college/institution and should be either students or professors in order to create/join a contingent.</marquee>
        <div class="example-box-wrapper">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="{{ form.gesid1.id_for_label }}">GES ID 1:</label>
                    <div class="col-sm-6">
                      {{ form.gesid1 }}
                      <p style="font-size: 13px; color: red">
                        *Your GES ID
                      </p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="{{ form.gesid2.id_for_label }}">GES ID 2:</label>
                    <div class="col-sm-6">
                      {{ form.gesid2 }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="{{ form.gesid3.id_for_label }}">GES ID 3:</label>
                    <div class="col-sm-6">
                      {{ form.gesid3 }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="{{ form.gesid4.id_for_label }}">GES ID 4:</label>
                    <div class="col-sm-6">
                      {{ form.gesid4 }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="{{ form.gesid5.id_for_label }}">GES ID 5:</label>
                    <div class="col-sm-6">
                      {{ form.gesid5 }}
                    </div>
                </div>
                <div class="text-center pad20A mrg15T" style="margin-bottom: 50px !important;">
                  <button class="btn btn-lg btn-info" id="submit">Create Contingent</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
</script>
<script>
    $('form').submit(function (e) {
        $('#errors').empty();
        $('#errorMessage').css('display', 'none');
        e.preventDefault();
        var gesid1 = $('#id_gesid1').val();
        var data = $('form').serialize()+'&gesid1='+gesid1;
        console.log(data);
        $("#submit").html("<div class=\"glyph-icon remove-border demo-icon tooltip-button icon-spin-4 icon-spin\" title=\"\" data-original-title=\"icon-spin-4\"></div>Validating Data");
        $("#loading").css('display','block');
        $("#loading").css('opacity','0.5');
        $("#loading").css('background','#000');

        $.ajax({
           url: './validate',
           cache: false,
           data: data,
           type: 'POST',
           success: function(data){
             console.log(data)
               if (data['status']){
                   console.log(data.id);
                   window.open('../view-contingent', '_self');
               } else{
                 $('#errorMessage').css('display', 'block');
                 $.each(data['errorMessage'], function(index, value){
                    $('#errors').append('<div class="alert alert-danger"><div class="bg-red alert-icon"><i class="glyph-icon icon-warning"></i></div><div class="alert-content"><h4 class="alert-title">Exception</h4><p>'+value+'</p></div></div>');                 });
               }
               $("#submit").html("Update Information");
               $("#loading").css('display','none');
           },
           error: function(data){
               $("#submit").html("Update Information");
               $("#loading").css('display','none');
               console.log(data);
          }
       });
    });
</script>

{% endblock %}

templates/login/join.html
{% extends 'login/base.html' %}

{% block content %}
    {% if error %}
      <div class="panel" id="errorMessage">
        <div class="panel-body">
            <h3 class="title-hero">Resolve the following errors.</h3>
            <div class="example-box-wrapper" id="errors">
                <div class="alert alert-danger">
                    <div class="bg-red alert-icon"><i class="glyph-icon icon-warning"></i></div>
                    <div class="alert-content">
                        <h4 class="alert-title">{{ error }}</h4>
                        <p>{{ errorMessage }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
   
      {% if success %}
      <div class="panel" id="successMessage">
        <div class="panel-body">
          <h3 class="title-hero">Information</h3>
          <div class="example-box-wrapper" id="success">
            <div class="alert alert-success">
              <div class="bg-green alert-icon"><i class="glyph-icon icon-check"></i></div>
              <div class="alert-content">
                <h4 class="alert-title">{{ success }}</h4>
                <p>{{ successMessage }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
    {% if form %}
    <div class="panel">
        <div class="panel-body">
            <h3 class="title-hero">Join Contingent: GES 2019</h3>
            <div class="example-box-wrapper">
                <form class="form-horizontal" method="post" action="./">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="{{ form.uid.id_for_label }}">Contingent ID:</label>
                        <div class="col-sm-6">
                          {{ form.uid }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="{{ form.captcha.id_for_label }}">Contingent Password:</label>
                        <div class="col-sm-6">
                          {{ form.captcha }}
                        </div>
                    </div>
                    <div class="text-center pad20A mrg15T" style="margin-bottom: 50px !important;">
                <button class="btn btn-lg btn-info" id="submit">Join Contingent</button>
            </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}

<script>
    $('frm').submit(function (e) {
        e.preventDefault();
        var gesid1 = $('#id_gesid1').val();
        var data = $('form').serialize();
        console.log(data);
        $("#submit").html("<div class=\"glyph-icon remove-border demo-icon tooltip-button icon-spin-4 icon-spin\" title=\"\" data-original-title=\"icon-spin-4\"></div>Validating Data");
        $("#loading").css('display','block');
        $("#loading").css('opacity','0.5');
        $("#loading").css('background','#000');

        $.ajax({
           url: './validate',
           cache: false,
           data: data,
           type: 'POST',
           success: function(data){
             console.log(data)
               if (data['status']){
                   console.log(data.id);
//                    window.open('./', '_self');
               } else{
                 $('#errors').append('<div class="alert alert-danger"><div class="bg-red alert-icon"><i class="glyph-icon icon-warning"></i></div><div class="alert-content"><h4 class="alert-title">Exception</h4><p>'+data['errorMessage']+'</p></div></div>');
                   alert(data['errorMessage']);
               }
               $("#submit").html("Update Information");
               $("#loading").css('display','none');
           },
           error: function(data){
               $("#submit").html("Update Information");
               $("#loading").css('display','none');
               console.log(data);
          }
       });
    });
</script>

{% endblock %}

templates/login/payment.html
{% extends 'login/base.html' %}


{% block content %}

  {% if userdata.contingent and not userdata.admin %}
        <div class="panel" id="errorMessage">
            <div class="panel-body">
                <h3 class="title-hero">Information</h3>
                <div class="example-box-wrapper">
                    <div class="alert alert-notice" id="categoryError">
                        <div class="bg-blue alert-icon"><i class="glyph-icon icon-info"></i></div>
                        <div class="alert-content">
                            <h4 class="alert-title">Unauthorized to access</h4>
                            <p>Your participation fees will be paid by your contingent admin.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  {% else %}
    <div class="panel">
      <div class="panel-body">
          <h3 class="title-hero">Payment</h3>
          <div class="example-box-wrapper">
              <form class="form-horizontal" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                      <label class="col-sm-3 control-label" for="{{ form.arrival.id_for_label }}">Arrival:</label>
                      <div class="col-sm-6">
                        {{ form.arrival }}
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-3 control-label" for="{{ form.departure.id_for_label }}">Departure:</label>
                      <div class="col-sm-6">
                        {{ form.departure }}
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-3 control-label" for="{{ form.pnr.id_for_label }}">PNR:</label>
                      <div class="col-sm-6">
                        {{ form.pnr }}
                      </div>
                  </div>
                  <div class="text-center pad20A mrg15T" style="margin-bottom: 50px !important;">
                    <button class="btn btn-lg btn-info" id="submit">Submit</button>
                  </div>
              </form>
          </div>
    </div>
  </div>
  {% endif %}

{% endblock %}

templates/login/post_reg_empresario.html
{% extends 'login/base.html' %}


{% block content %}
<style>
        .form-group{
            margin-top: 20px !important;
            margin-bottom: 20px !important;
        }
 </style>

<div class="panel">
    <div class="panel-body">
        <h3 class="title-hero">Additional Details: GES 2019</h3>
        <div class="example-box-wrapper">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="{{ form.size.id_for_label }}">Team Size(including you)</label>
                    <div class="col-sm-6">
                      {{ form.size }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="{{ form.acco.id_for_label }}">Do you need accomodation?</label>
                    <div class="col-sm-6">
                        <div class="row">
                            {% for type in form.acco %}
                                <div class="col-sm-6">
                                    {{ type }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="text-center pad20A mrg15T" style="margin-bottom: 50px !important;">
            <button class="btn btn-lg btn-info" id="submit">Update Information</button>
        </div>
            </form>
        </div>
    </div>
</div>

<script>
    $('#submit').click(function (e) {
        const size = $('#id_size').val();
        const acco = $("[name='acco']:checked").val();
        if(acco && size){
            e.preventDefault();
            console.log($("form").serialize());
            $("#submit").html("<div class=\"glyph-icon remove-border demo-icon tooltip-button icon-spin-4 icon-spin\" title=\"\" data-original-title=\"icon-spin-4\"></div>Validating Data");
            $("#loading").css('display','block');
            $("#loading").css('opacity','0.5');
            $("#loading").css('background','#000');

            $.ajax({
               url: 'validate/post-reg-empresario',
               cache: false,
               data: $("form").serialize(),
               type: 'POST',
               success: function(data){
                   if (data === 'saved'){
                       window.open('./', '_self');
                   } else{
                       alert(data);
                   }
               },
               error: function(data){
                   $("#submit").html("Update Information");
                   $("#loading").css('display','none');
                   console.log(data);
              }
           });
        }
    });
</script>
{% endblock %}